### ISSUE TITLE
https://github.com/Andrii97/TPPS/blob/master/EuroDiffusion/src/main/java/ua/kpi/App.java#L42

### ISSUE THREAD

**Issue by vladaerastova** [Andrii97/TPPS#3]
https://github.com/Andrii97/TPPS/blob/51e2fa799cbac67018add92b16b3bb139de9e0ad/EuroDiffusion/src/main/java/ua/kpi/App.java#L42

Probably, in this function after getting all countries you should check whether at least one city of the country has neighbor city from another country. Otherwise, if the country has no neighbors, it will never be completed and your program will never stop.

**Comment by AndriiSeverin** [comment]
This problem was fixed by adding the limitation to the number of days that is simulated. Now the highest value of days that is simulated equals to 20000.
